// <auto-generated>
namespace echo.primary.core.h2tp;

public enum Header{
/*
Acceptable instance-manipulations for the request.

A-IM: feed
*/

AIM,
/*
Media type(s) that is/are acceptable for the response. See Content negotiation.

Accept: text/html
*/

Accept,
/*
Character sets that are acceptable.

Accept-Charset: utf-8
*/

AcceptCharset,
/*
Acceptable version in time.

Accept-Datetime: Thu, 31 May 2007 20:35:00 GMT
*/

AcceptDatetime,
/*
List of acceptable encodings. See HTTP compression.

Accept-Encoding: gzip, deflate
*/

AcceptEncoding,
/*
List of acceptable human languages for response. See Content negotiation.

Accept-Language: en-US
*/

AcceptLanguage,
/*
Initiates a request for cross-origin resource sharing with Origin (below).

Access-Control-Request-Method: GET
*/

AccessControlRequestMethod,
AccessControlRequestHeaders,
/*
Authentication credentials for HTTP authentication.

Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==
*/

Authorization,
/*
Used to specify directives that must be obeyed by all caching mechanisms along the request-response chain.

Cache-Control: no-cache
*/

CacheControl,
/*
Control options for the current connection and list of hop-by-hop request fields.
Must not be used with HTTP/2.

Connection: keep-alive
Connection: Upgrade
*/

Connection,
/*
The type of encoding used on the data. See HTTP compression.

Content-Encoding: gzip
*/

ContentEncoding,
/*
The length of the request body in octets (8-bit bytes).

Content-Length: 348
*/

ContentLength,
/*
A Base64-encoded binary MD5 sum of the content of the request body.

Content-MD5: Q2hlY2sgSW50ZWdyaXR5IQ==
*/

ContentMD5,
/*
The Media type of the body of the request (used with POST and PUT requests).

Content-Type: application/x-www-form-urlencoded
*/

ContentType,
/*
An HTTP cookie previously sent by the server with Set-Cookie (below).

Cookie: $Version=1; Skin=new;
*/

Cookie,
/*
The date and time at which the message was originated (in "HTTP-date" format as defined by RFC 9110: HTTP Semantics, section 5.6.7 "Date/Time Formats").

Date: Tue, 15 Nov 1994 08:12:31 GMT
*/

Date,
/*
Indicates that particular server behaviors are required by the client.

Expect: 100-continue
*/

Expect,
/*
Disclose original information of a client connecting to a web server through an HTTP proxy.

Forwarded: for=192.0.2.60;proto=http;by=203.0.113.43 Forwarded: for=192.0.2.43, for=198.51.100.17
*/

Forwarded,
/*
The email address of the user making the request.

From: user@example.com
*/

From,
/*
The domain name of the server (for virtual hosting), and the TCP port number on which the server is listening. The port number may be omitted if the port is the standard port for the service requested.
Mandatory since HTTP/1.1.
If the request is generated directly in HTTP/2, it should not be used.

Host: en.wikipedia.org:8080
Host: en.wikipedia.org
*/

Host,
/*
A request that upgrades from HTTP/1.1 to HTTP/2 MUST include exactly one HTTP2-Settings header field. The HTTP2-Settings header field is a connection-specific header field that includes parameters that govern the HTTP/2 connection, provided in anticipation of the server accepting the request to upgrade.

HTTP2-Settings: token64
*/

HTTP2Settings,
/*
Only perform the action if the client supplied entity matches the same entity on the server. This is mainly for methods like PUT to only update a resource if it has not been modified since the user last updated it.

If-Match: "737060cd8c284d8af7ad3082f209582d"
*/

IfMatch,
/*
Allows a 304 Not Modified to be returned if content is unchanged.

If-Modified-Since: Sat, 29 Oct 1994 19:43:31 GMT
*/

IfModifiedSince,
/*
Allows a 304 Not Modified to be returned if content is unchanged, see HTTP ETag.

If-None-Match: "737060cd8c284d8af7ad3082f209582d"
*/

IfNoneMatch,
/*
If the entity is unchanged, send me the part(s) that I am missing; otherwise, send me the entire new entity.

If-Range: "737060cd8c284d8af7ad3082f209582d"
*/

IfRange,
/*
Only send the response if the entity has not been modified since a specific time.

If-Unmodified-Since: Sat, 29 Oct 1994 19:43:31 GMT
*/

IfUnmodifiedSince,
/*
Limit the number of times the message can be forwarded through proxies or gateways.

Max-Forwards: 10
*/

MaxForwards,
/*
Initiates a request for cross-origin resource sharing (asks server for Access-Control-* response fields).

Origin: http://www.example-social-network.com
*/

Origin,
/*
Implementation-specific fields that may have various effects anywhere along the request-response chain.

Pragma: no-cache
*/

Pragma,
/*
Allows client to request that certain behaviors be employed by a server while processing a request.

Prefer: return=representation
*/

Prefer,
/*
Authorization credentials for connecting to a proxy.

Proxy-Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==
*/

ProxyAuthorization,
/*
Request only part of an entity.  Bytes are numbered from 0.  See Byte serving.

Range: bytes=500-999
*/

Range,
/*
This is the address of the previous web page from which a link to the currently requested page was followed. (The word "referrer" has been misspelled in the RFC as well as in most implementations to the point that it has become standard usage and is considered correct terminology)

Referer: http://en.wikipedia.org/wiki/Main_Page
*/

Referer,
/*
The transfer encodings the user agent is willing to accept: the same values as for the response header field Transfer-Encoding can be used, plus the "trailers" value (related to the "chunked" transfer method) to notify the server it expects to receive additional fields in the trailer after the last, zero-sized, chunk.
Only trailers is supported in HTTP/2.

TE: trailers, deflate
*/

TE,
/*
The Trailer general field value indicates that the given set of header fields is present in the trailer of a message encoded with chunked transfer coding.

Trailer: Max-Forwards
*/

Trailer,
/*
The form of encoding used to safely transfer the entity to the user. Currently defined methods are: chunked, compress, deflate, gzip, identity.
Must not be used with HTTP/2.

Transfer-Encoding: chunked
*/

TransferEncoding,
/*
The user agent string of the user agent.

User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:12.0) Gecko/20100101 Firefox/12.0
*/

UserAgent,
/*
Ask the server to upgrade to another protocol.
Must not be used in HTTP/2.

Upgrade: h2c, HTTPS/1.3, IRC/6.9, RTA/x11, websocket
*/

Upgrade,
/*
Informs the server of proxies through which the request was sent.

Via: 1.0 fred, 1.1 example.com (Apache/1.1)
*/

Via,
/*
A general warning about possible problems with the entity body.

Warning: 199 Miscellaneous warning
*/

Warning,
/*
Tells a server which (presumably in the middle of a HTTP -> HTTPS migration) hosts mixed content that the client would prefer redirection to HTTPS and can handle Content-Security-Policy: upgrade-insecure-requests
Must not be used with HTTP/2

Upgrade-Insecure-Requests: 1
*/

UpgradeInsecureRequests,
/*
Mainly used to identify Ajax requests (most JavaScript frameworks send this field with value of XMLHttpRequest); also identifies Android apps using WebView

X-Requested-With: XMLHttpRequest
*/

XRequestedWith,
/*
Requests a web application to disable their tracking of a user. This is Mozilla's version of the X-Do-Not-Track header field (since Firefox 4.0 Beta 11).  Safari and IE9 also have support for this field.

DNT: 1 (Do Not Track Enabled)
DNT: 0 (Do Not Track Disabled)
*/

DNT,
/*
A de facto standard for identifying the originating IP address of a client connecting to a web server through an HTTP proxy or load balancer. Superseded by Forwarded header.

X-Forwarded-For: client1, proxy1, proxy2
X-Forwarded-For: 129.78.138.66, 129.78.64.103
*/

XForwardedFor,
/*
A de facto standard for identifying the original host requested by the client in the Host HTTP request header, since the host name and/or port of the reverse proxy (load balancer) may differ from the origin server handling the request. Superseded by Forwarded header.

X-Forwarded-Host: en.wikipedia.org:8080
X-Forwarded-Host: en.wikipedia.org
*/

XForwardedHost,
/*
A de facto standard for identifying the originating protocol of an HTTP request, since a reverse proxy (or a load balancer) may communicate with a web server using HTTP even if the request to the reverse proxy is HTTPS.  An alternative form of the header (X-ProxyUser-Ip) is used by Google clients talking to Google servers. Superseded by Forwarded header.

X-Forwarded-Proto: https
*/

XForwardedProto,
/*
Non-standard header field used by Microsoft applications and load-balancers

Front-End-Https: on
*/

FrontEndHttps,
/*
Requests a web application to override the method specified in the request (typically POST) with the method given in the header field (typically PUT or DELETE). This can be used when a user agent or firewall prevents PUT or DELETE methods from being sent directly (note that this is either a bug in the software component, which ought to be fixed, or an intentional configuration, in which case bypassing it may be the wrong thing to do).

X-HTTP-Method-Override: DELETE
*/

XHttpMethodOverride,
/*
Allows easier parsing of the MakeModel/Firmware that is usually found in the User-Agent String of AT&T Devices

X-Att-Deviceid: GT-P7320/P7320XXLPG
*/

XATTDeviceId,
/*
Links to an XML file on the Internet with a full description and details about the device currently connecting. In the example to the right is an XML file for an AT&T Samsung Galaxy S2.

x-wap-profile: http://wap.samsungmobile.com/uaprof/SGH-I777.xml
*/

XWapProfile,
/*
Implemented as a misunderstanding of the HTTP specifications. Common because of mistakes in implementations of early HTTP versions. Has exactly the same functionality as standard Connection field.
Must not be used with HTTP/2.

Proxy-Connection: keep-alive
*/

ProxyConnection,
/*
Server-side deep packet inspection of a unique ID identifying customers of Verizon Wireless; also known as "perma-cookie" or "supercookie"

X-UIDH: ...
*/

XUIDH,
/*
Used to prevent cross-site request forgery. Alternative header names are: X-CSRFToken

X-Csrf-Token: i8XNjC4b8KVok4uw5RftR38Wgp2BFwql
*/

XCsrfToken,
/*
Correlates HTTP requests between a client and server.

X-Request-ID: f058ebd6-02f7-4d3f-942e-904344e8cde5
*/

XRequestID,
XCorrelationID,
CorrelationID,
/*
The Save-Data client hint request header available in Chrome, Opera, and Yandex browsers lets developers deliver lighter, faster applications to users who opt-in to data saving mode in their browser.

Save-Data: on
*/

SaveData,
/*
The Sec-GPC (Global Privacy Control) request header indicates whether the user consents to a website or service selling or sharing their personal information with third parties.

Sec-GPC: 1
*/

SecGPC,
/*
Requests HTTP Client Hints

Accept-CH: UA, Platform
*/

AcceptCH,
/*
Specifying which web sites can participate in cross-origin resource sharing

Access-Control-Allow-Origin: *
*/

AccessControlAllowOrigin,
AccessControlAllowCredentials,
AccessControlExposeHeaders,
AccessControlMaxAge,
AccessControlAllowMethods,
AccessControlAllowHeaders,
/*
Specifies which patch document formats this server supports

Accept-Patch: text/example;charset=utf-8
*/

AcceptPatch,
/*
What partial content range types this server supports via byte serving

Accept-Ranges: bytes
*/

AcceptRanges,
/*
The age the object has been in a proxy cache in seconds

Age: 12
*/

Age,
/*
Valid methods for a specified resource. To be used for a 405 Method not allowed

Allow: GET, HEAD
*/

Allow,
/*
A server uses "Alt-Svc" header (meaning Alternative Services) to indicate that its resources can also be accessed at a different network location (host or port) or using a different protocol
When using HTTP/2, servers should instead send an ALTSVC frame.

Alt-Svc: http/1.1="http2.example.com:8001"; ma=7200
*/

AltSvc,
/*
Tells all caching mechanisms from server to client whether they may cache this object. It is measured in seconds

Cache-Control: max-age=3600
*/

/*
Control options for the current connection and list of hop-by-hop response fields.
Must not be used with HTTP/2.

Connection: close
*/

/*
An opportunity to raise a "File Download" dialogue box for a known MIME type with binary format or suggest a filename for dynamic content. Quotes are necessary with special characters.

Content-Disposition: attachment; filename="fname.ext"
*/

ContentDisposition,
/*
The type of encoding used on the data. See HTTP compression.

Content-Encoding: gzip
*/

/*
The natural language or languages of the intended audience for the enclosed content

Content-Language: da
*/

ContentLanguage,
/*
The length of the response body in octets (8-bit bytes)

Content-Length: 348
*/

/*
An alternate location for the returned data

Content-Location: /index.htm
*/

ContentLocation,
/*
A Base64-encoded binary MD5 sum of the content of the response

Content-MD5: Q2hlY2sgSW50ZWdyaXR5IQ==
*/

/*
Where in a full body message this partial message belongs

Content-Range: bytes 21010-47021/47022
*/

ContentRange,
/*
The MIME type of this content

Content-Type: text/html; charset=utf-8
*/

/*
The date and time that the message was sent (in "HTTP-date" format as defined by RFC 9110)

Date: Tue, 15 Nov 1994 08:12:31 GMT
*/

/*
Specifies the delta-encoding entity tag of the response.

Delta-Base: "abc"
*/

DeltaBase,
/*
An identifier for a specific version of a resource, often a message digest

ETag: "737060cd8c284d8af7ad3082f209582d"
*/

ETag,
/*
Gives the date/time after which the response is considered stale (in "HTTP-date" format as defined by RFC 9110)

Expires: Thu, 01 Dec 1994 16:00:00 GMT
*/

Expires,
/*
Instance-manipulations applied to the response.

IM: feed
*/

IM,
/*
The last modified date for the requested object (in "HTTP-date" format as defined by RFC 9110)

Last-Modified: Tue, 15 Nov 1994 12:45:26 GMT
*/

LastModified,
/*
Used to express a typed relationship with another resource, where the relation type is defined by RFC 5988

Link: </feed>; rel="alternate"
*/

Link,
/*
Used in redirection, or when a new resource has been created.

Example 1: Location: http://www.w3.org/pub/WWW/People.html
Example 2: Location: /pub/WWW/People.html
*/

Location,
/*
This field is supposed to set P3P policy, in the form of P3P:CP="your_compact_policy". However, P3P did not take off, most browsers have never fully implemented it, a lot of websites set this field with fake policy text, that was enough to fool browsers the existence of P3P policy and grant permissions for third party cookies.

P3P: CP="This is not a P3P policy! See https://en.wikipedia.org/wiki/Special:CentralAutoLogin/P3P for more info."
*/

P3P,
/*
Implementation-specific fields that may have various effects anywhere along the request-response chain.

Pragma: no-cache
*/

/*
Indicates which Prefer tokens were honored by the server and applied to the processing of the request.

Preference-Applied: return=representation
*/

PreferenceApplied,
/*
Request authentication to access the proxy.

Proxy-Authenticate: Basic
*/

ProxyAuthenticate,
/*
HTTP Public Key Pinning, announces hash of website's authentic TLS certificate

Public-Key-Pins: max-age=2592000; pin-sha256="E9CZ9INDbd+2eRQozYqqbQ2yXLVKB9+xcprMF+44U1g=";
*/

PublicKeyPins,
/*
If an entity is temporarily unavailable, this instructs the client to try again later. Value could be a specified period of time (in seconds) or a HTTP-date.

Example 1: Retry-After: 120
Example 2: Retry-After: Fri, 07 Nov 2014 23:59:59 GMT
*/

RetryAfter,
/*
A name for the server

Server: Apache/2.4.1 (Unix)
*/

Server,
/*
An HTTP cookie

Set-Cookie: UserID=JohnDoe; Max-Age=3600; Version=1
*/

SetCookie,
/*
A HSTS Policy informing the HTTP client how long to cache the HTTPS only policy and whether this applies to subdomains.

Strict-Transport-Security: max-age=16070400; includeSubDomains
*/

StrictTransportSecurity,
/*
The Trailer general field value indicates that the given set of header fields is present in the trailer of a message encoded with chunked transfer coding.

Trailer: Max-Forwards
*/

/*
The form of encoding used to safely transfer the entity to the user. Currently defined methods are: chunked, compress, deflate, gzip, identity.
Must not be used with HTTP/2.

Transfer-Encoding: chunked
*/

/*
Tracking Status header, value suggested to be sent in response to a DNT(do-not-track), possible values:
"!" — under construction
"?" — dynamic
"G" — gateway to multiple parties
"N" — not tracking
"T" — tracking
"C" — tracking with consent
"P" — tracking only if consented
"D" — disregarding DNT
"U" — updated

Tk: ?
*/

Tk,
/*
Ask the client to upgrade to another protocol.
Must not be used in HTTP/2

Upgrade: h2c, HTTPS/1.3, IRC/6.9, RTA/x11, websocket
*/

/*
Tells downstream proxies how to match future request headers to decide whether the cached response can be used rather than requesting a fresh one from the origin server.

Example 1: Vary: *
Example 2: Vary: Accept-Language
*/

Vary,
/*
Informs the client of proxies through which the response was sent.

Via: 1.0 fred, 1.1 example.com (Apache/1.1)
*/

/*
A general warning about possible problems with the entity body.

Warning: 199 Miscellaneous warning
*/

/*
Indicates the authentication scheme that should be used to access the requested entity.

WWW-Authenticate: Basic
*/

WWWAuthenticate,
/*
Clickjacking protection: deny - no rendering within a frame, sameorigin - no rendering if origin mismatch, allow-from - allow from specified location, allowall - non-standard, allow from any location

X-Frame-Options: deny
*/

XFrameOptions,
/*
Content Security Policy definition.

X-WebKit-CSP: default-src 'self'
*/

ContentSecurityPolicy,
XContentSecurityPolicy,
XWebKitCSP,
/*
Notify to prefer to enforce Certificate Transparency.

Expect-CT: max-age=604800, enforce, report-uri="https://example.example/report"
*/

ExpectCT,
/*
Used to configure network request logging.

NEL: { "report_to": "name_of_reporting_group", "max_age": 12345, "include_subdomains": false, "success_fraction": 0.0, "failure_fraction": 1.0 }
*/

NEL,
/*
To allow or disable different features or APIs of the browser.

Permissions-Policy: fullscreen=(), camera=(), microphone=(), geolocation=(), interest-cohort=()
*/

PermissionsPolicy,
/*
Used in redirection, or when a new resource has been created.  This refresh redirects after 5 seconds. Header extension introduced by Netscape and supported by most web browsers. Defined by HTML Standard

Refresh: 5; url=http://www.w3.org/pub/WWW/People.html
*/

Refresh,
/*
Instructs the user agent to store reporting endpoints for an origin.

Report-To: { "group": "csp-endpoint", "max_age": 10886400, "endpoints":  }
*/

ReportTo,
/*
CGI header field specifying the status of the HTTP response. Normal HTTP responses use a separate "Status-Line" instead, defined by RFC 9110.

Status: 200 OK
*/

Status,
/*
The Timing-Allow-Origin response header specifies origins that are allowed to see values of attributes retrieved via features of the Resource Timing API, which would otherwise be reported as zero due to cross-origin restrictions.

Timing-Allow-Origin: *
Timing-Allow-Origin: <origin>*
*/

TimingAllowOrigin,
/*
Provide the duration of the audio or video in seconds; only supported by Gecko browsers

X-Content-Duration: 42.666
*/

XContentDuration,
/*
The only defined value, "nosniff", prevents Internet Explorer from MIME-sniffing a response away from the declared content-type. This also applies to Google Chrome, when downloading extensions.

X-Content-Type-Options: nosniff
*/

XContentTypeOptions,
/*
Specifies the technology (e.g. ASP.NET, PHP, JBoss) supporting the web application (version details are often in X-Runtime, X-Version, or X-AspNet-Version)

X-Powered-By: PHP/5.4.0
*/

XPoweredBy,
/*
Specifies the component that is responsible for a particular redirect.

X-Redirect-By: WordPressX-Redirect-By: Polylang
*/

XRedirectBy,
/*
Correlates HTTP requests between a client and server.

X-Request-ID: f058ebd6-02f7-4d3f-942e-904344e8cde5
*/

/*
Recommends the preferred rendering engine (often a backward-compatibility mode) to use to display the content. Also used to activate Chrome Frame in Internet Explorer. In HTML Standard, only the IE=edge value is defined.        

X-UA-Compatible: IE=edgeX-UA-Compatible: IE=EmulateIE7X-UA-Compatible: Chrome=1
*/

XUACompatible,
/*
Cross-site scripting (XSS) filter

X-XSS-Protection: 1; mode=block
*/

XXSSProtection,
}
