import requests

from bs4 import BeautifulSoup
import re


resp = requests.get(
    "https://en.wikipedia.org/wiki/List_of_HTTP_header_fields",
    proxies={"https": "http://127.0.0.1:7891"},
)
html = BeautifulSoup(resp.text, "lxml")

lst = []


def remove_link_ref(v: str) -> str:
    return re.sub(r"\[.*\]", "", v)


for tr in html.select("tr"):
    tds = tr.select("td")

    if len(tds) < 3:
        continue

    names: str
    names = tds[0].text.strip()
    names = list(map(lambda x: x.strip(), remove_link_ref(names).split(",")))

    obj = {
        "names": names,
        "desc": remove_link_ref(tds[1].text).strip(),
        "example": remove_link_ref(tds[2].text).strip(),
    }

    lst.append(obj)

buf = [
    """// <auto-generated>
namespace echo.primary.core.h2tp;

public enum Header{"""
]

ns = set()

for obj in lst:
    buf.append("/*")
    buf.append(obj["desc"])
    buf.append("")
    buf.append(obj["example"])
    buf.append("*/")
    buf.append("")

    for name in obj["names"]:
        if name in ns:
            continue

        ns.add(name)
        buf.append(f"{name.replace("-", "")},")

buf.append("}")

print("\r\n".join(buf))