using System;
using System.Text;
using Microsoft.CodeAnalysis;

namespace cg {
	[Generator]
	public class ImplIAsyncReaderForTcpConnection : ISourceGenerator {
		void ISourceGenerator.Execute(GeneratorExecutionContext context) {
			var sb = new StringBuilder();
			sb.Append(@"// <auto-generated>
namespace echo.primary.core.net;

public partial class TcpConnection {
	public void X(){}
");
			sb.Append("}");
			Console.Write(sb.ToString());
			context.AddSource("core.net.TcpConnection.g.cs", sb.ToString());
		}

		void ISourceGenerator.Initialize(GeneratorInitializationContext context) {
		}
	}
}